### ISSUE TITLE
Add any JAVA code

### ISSUE THREAD

**Issue by nayyyhaa** [nayyyhaa/JAVA-PROGRAMMING#2]
Add any JAVA code or tricks in the respective folders
Example - Exceptional Handling questions in the Exceptional Handling folder, etc.

**Comment by c99SRS** [comment]
Hi @nayyyhaa , Can I work on this?

**Comment by nayyyhaa** [comment]
> Hi @nayyyhaa , Can I work on this?

Yes, sure. All contributions are welcome. :)

**Comment by c99SRS** [comment]
Hi @nayyyhaa , added one question and renamed the files. Please review and merge it.

**Comment by Rohit-2602** [comment]
@nayyyhaa Can i add some sorting algorithm to it??

**Comment by nayyyhaa** [comment]
> @nayyyhaa Can i add some sorting algorithm to it??

Yes, you can.

**Comment by awalker20** [comment]
Hi, can I add a merge sort example?

**Comment by johnjajeh** [comment]
Are there any topics that haven't been addressed that you think should be in the repository?
